import 'package:flutter/material.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';

// TODO: rename fiule to my_icons.dart
class MyIcons {
  static const List<IconData> expenseIcons = [
    MdiIcons.silverware,
    MdiIcons.car,
    MdiIcons.cart,
    MdiIcons.movie,
    MdiIcons.emoticonOutline,
    MdiIcons.medicalBag,
    MdiIcons.home,
    MdiIcons.airplane,
    MdiIcons.accountMultiple,
    MdiIcons.school,
    MdiIcons.folderDownload,
    MdiIcons.accountCash,
    MdiIcons.apple,
    MdiIcons.baguette,
    MdiIcons.balloon,
    MdiIcons.microsoftXboxController,
    MdiIcons.audioVideo,
    MdiIcons.babyFaceOutline,
    MdiIcons.axe,
    MdiIcons.bedKing,
    MdiIcons.blender,
    MdiIcons.bike,
    MdiIcons.bugle,
    MdiIcons.brush,
    MdiIcons.bowlMix,
    MdiIcons.camera,
    MdiIcons.campfire,
    MdiIcons.cannabis,
    MdiIcons.candycane,
    MdiIcons.candle,
    MdiIcons.cat,
    MdiIcons.dog,
    MdiIcons.checkerboard,
    MdiIcons.cloud,
    MdiIcons.contentCut,
    MdiIcons.discord,
    MdiIcons.faceWoman,
    MdiIcons.face,
    MdiIcons.ferry,
    MdiIcons.ferrisWheel,
    MdiIcons.fuel,
    MdiIcons.glassMug,
    MdiIcons.heart,
    MdiIcons.iceCream,
    MdiIcons.phone,
    MdiIcons.tennis,
    MdiIcons.watch,
    MdiIcons.toyBrick,
    MdiIcons.telescope,
    MdiIcons.spotify,
    MdiIcons.origin,
    MdiIcons.dumbbell,
    MdiIcons.hanger,
    MdiIcons.tshirtCrew,
    MdiIcons.fish,
  ];

  static const List<IconData> incomeIcons = [
    MdiIcons.currencyUsd,
    MdiIcons.walletGiftcard,
    MdiIcons.briefcase,
    MdiIcons.bank,
    MdiIcons.homeGroup,
    MdiIcons.swapVerticalBold,
    MdiIcons.folderUpload,
    MdiIcons.baguette,
    MdiIcons.balloon,
    MdiIcons.currencyBtc,
    MdiIcons.seed,
    MdiIcons.brush,
    MdiIcons.carSide,
    MdiIcons.chartBar,
    MdiIcons.fish,
    MdiIcons.footballHelmet,
    MdiIcons.gamepad,
    MdiIcons.hatFedora,
    MdiIcons.watermark,
    MdiIcons.tabletAndroid
  ];
}